######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 15 11:49:40 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myVlcPlayer.h
FORMS += myVlcPlayer.ui
SOURCES += main.cpp myVlcPlayer.cpp
