######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 15 17:45:00 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
FORMS += mainWindow.ui
SOURCES += main.cpp mainWindow.cpp
